version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"  # Keeps your original port mapping
    env_file:
      - .env         # Uses your local .env file
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Neema@@24
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: Neema@@24
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
